// =============================================================================
// cpu_top_tb.sv  --  full-RV32I spec for the CPU. Do NOT edit this.
// =============================================================================
// Run with:  make sim TB=cpu_top
//
// Loads programs/cpu_test_full.hex (a program that exercises EVERY RV32I
// instruction class) and checks the resulting registers via the writeback
// "shadow" (watch the debug taps, record each register write, compare at the end).
//
// NOTE: exercises the full RV32I instruction set (lui/auipc/jal/jalr, all six
// branches, and every byte/half/word load-store width), not just the R-type/
// I-ALU/lw/sw/beq subset the core started with.
//
// Expected values were generated by a reference RV32I assembler+simulator.
// =============================================================================
`timescale 1ns/1ps

module cpu_top_tb;

    logic        clk = 0, rst_n;
    logic [31:0] debug_pc, debug_result;
    logic        debug_reg_write;
    logic [4:0]  debug_rd;
    logic        uart_tx, halt;   // SoC ports added after this tb was written; unused here

    int          errors = 0;
    logic [31:0] shadow [0:31];

    cpu_top dut (.*);
    defparam dut.u_imem.INIT_FILE = "programs/cpu_test_full.hex";

    always #5 clk = ~clk;

    task automatic check(input string name, input int idx, input logic [31:0] exp);
        if (shadow[idx] !== exp) begin
            $display("  FAIL x%0d %-18s got 0x%08x  expected 0x%08x", idx, name, shadow[idx], exp);
            errors++;
        end else begin
            $display("  ok   x%0d %-18s 0x%08x", idx, name, shadow[idx]);
        end
    endtask

    initial begin
        $dumpfile("cpu_top_tb.vcd");
        $dumpvars(0, cpu_top_tb);

        for (int i = 0; i < 32; i++) shadow[i] = 0;

        // reset released on a negedge (no race), then trace each writeback
        rst_n = 0;
        @(posedge clk);
        @(negedge clk);
        rst_n = 1;
        repeat (120) begin
            if (debug_reg_write === 1'b1 && debug_rd != 5'd0)
                shadow[debug_rd] = debug_result;
            @(negedge clk);
        end

        // ---- constants / existing R & I ops ----
        check("addi",        1,  32'h00000005);
        check("addi",        2,  32'h00000003);
        check("addi neg",    3,  32'hFFFFFFFF);
        check("add",         6,  32'h00000008);
        check("sub",         7,  32'h00000002);
        check("xor",         8,  32'h00000006);
        check("srai",        9,  32'hFABCDE00);

        // ---- upper-immediate ----
        check("lui",         4,  32'hABCDE000);
        check("auipc",       5,  32'h00001010);

        // ---- jumps (link = pc+4; both correctly skip a poison) ----
        check("jal  link",   10, 32'h0000002C);
        check("jal  body",   11, 32'h0000004D);   // 77
        check("jalr link",   12, 32'h0000003C);
        check("jalr body",   13, 32'h00000063);   // 99
        check("addr imm",    14, 32'h00000040);

        // ---- branches taken (each skipped its poison) ----
        check("beq  taken",  15, 32'h0000000A);   // 10
        check("bne  taken",  16, 32'h0000000B);   // 11
        check("blt  taken",  17, 32'h0000000C);   // 12
        check("bge  taken",  18, 32'h0000000D);   // 13
        check("bltu taken",  19, 32'h0000000E);   // 14
        check("bgeu taken",  20, 32'h0000000F);   // 15

        // ---- branches NOT taken (each fell through) ----
        check("beq  ntaken", 21, 32'h00000014);   // 20
        check("blt  ntaken", 22, 32'h00000015);   // 21
        check("bgeu ntaken", 23, 32'h00000016);   // 22

        // ---- loads / stores ----
        check("build val",   24, 32'h12345678);
        check("lw",          25, 32'h12345678);
        check("lbu",         26, 32'h00000078);
        check("lhu",         27, 32'h00001234);
        check("lb  sign",    28, 32'hFFFFFFFF);   // byte 0xFF -> -1
        check("lh  sign",    29, 32'hFFFFFFFF);   // half 0xFFFF -> -1
        check("sb  + lbu",   31, 32'h0000007B);   // 123 stored as byte, read back

        if (errors == 0) $display("CPU TOP (full RV32I): ALL TESTS PASSED");
        else             $display("CPU TOP (full RV32I): %0d FAILURE(S)", errors);
        $finish;
    end

endmodule
